/// FHE computation graphs for encrypted risk checks.
///
/// These functions are compiled by the `#[encrypt_fn]` macro into
/// DAGs of FHE operations. The Encrypt executor evaluates them
/// off-chain using real FHE and commits the results on-chain.
///
/// In the pre-alpha, values are stored as plaintext but the
/// computation graph infrastructure is fully functional.
///
/// NOTE: This file requires the `encrypt-dsl` crate which provides
/// the `#[encrypt_fn]` macro and encrypted types (EUint64, EBool).
/// It is kept separate from the main program to allow independent
/// compilation and to clearly isolate FHE logic.
///
/// When the encrypt-anchor crate is available and compatible with
/// our anchor-lang version, these functions would be imported and
/// called via EncryptContext CPI in the main program.

// The following would be enabled when encrypt-dsl is added to dependencies:
//
// use encrypt_dsl::prelude::encrypt_fn;
// use encrypt_types::encrypted::{EUint64, EBool};
//
// /// Check if a position size is within the allowed limit.
// /// Both values are encrypted -- the comparison happens in FHE.
// /// Only the boolean result needs to be decrypted.
// #[encrypt_fn]
// fn check_position_limit(position_size: EUint64, max_size: EUint64) -> EBool {
//     position_size <= max_size
// }
//
// /// Check if daily loss is within the allowed limit.
// #[encrypt_fn]
// fn check_daily_loss_limit(daily_loss: EUint64, max_loss: EUint64) -> EBool {
//     daily_loss <= max_loss
// }
//
// /// Check if drawdown is within the allowed limit.
// #[encrypt_fn]
// fn check_drawdown_limit(drawdown: EUint64, max_drawdown: EUint64) -> EBool {
//     drawdown <= max_drawdown
// }
//
// /// Update cumulative PnL by adding a new trade result.
// /// The running total stays encrypted throughout.
// #[encrypt_fn]
// fn update_cumulative_pnl(current_pnl: EUint64, trade_pnl: EUint64) -> EUint64 {
//     current_pnl + trade_pnl
// }
//
// /// Count total trades by incrementing an encrypted counter.
// #[encrypt_fn]
// fn increment_trade_count(count: EUint64) -> EUint64 {
//     count + 1
// }

/// Placeholder module documenting the FHE computation graphs
/// that would be generated by the encrypt_fn macro.
///
/// Each function compiles to a graph with specific inputs/outputs:
///
/// check_position_limit:
///   Inputs:  position_size (EUint64), max_size (EUint64)
///   Ops:     LessEqual
///   Outputs: result (EBool)
///
/// check_daily_loss_limit:
///   Inputs:  daily_loss (EUint64), max_loss (EUint64)
///   Ops:     LessEqual
///   Outputs: result (EBool)
///
/// update_cumulative_pnl:
///   Inputs:  current_pnl (EUint64), trade_pnl (EUint64)
///   Ops:     Add
///   Outputs: new_pnl (EUint64)
pub mod fhe_graphs {
    /// FHE type identifiers matching Encrypt's type system.
    pub const FHE_TYPE_EUINT64: u8 = 4;
    pub const FHE_TYPE_EBOOL: u8 = 0;

    /// Graph names for client-side reference.
    pub const CHECK_POSITION_LIMIT: &str = "check_position_limit";
    pub const CHECK_DAILY_LOSS_LIMIT: &str = "check_daily_loss_limit";
    pub const CHECK_DRAWDOWN_LIMIT: &str = "check_drawdown_limit";
    pub const UPDATE_CUMULATIVE_PNL: &str = "update_cumulative_pnl";
    pub const INCREMENT_TRADE_COUNT: &str = "increment_trade_count";
}
